- name: Install Docker
  hosts: localhost
  connection: local
  become: yes
  tasks:

    - name: Install Docker dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add stable Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
        update_cache: yes

    - name: Install latest Docker CE
      apt:
        pkg:
          - docker-ce
        state: present
        update_cache: yes
